#41: Ya realicé los cambios
cs1000-utec/labs pull request #47
Opened 2021-12-19 22:30 UTC by NoemiHuarino-utec

Buenas tardes profesor.
Nombre: Noemi Alejandra Huarino Anchillo
Motivo: Punto extra en la PC1
Horario: Laboratorio 1.01 (miércoles de 3 a 5pm)

2021-12-19 22:34 UTC, franciscovilchezv requested changes

2021-12-19 22:34 UTC, franciscovilchezv commented on lab8/README.md
> +Buscar las flores de especie `setosa` con una longitud de sepalo mayor a `4.8`.
Agregar tilde a sépalo

2021-12-19 22:48 UTC, NoemiHuarino-utec commented on lab8/README.md
> +Buscar las flores de especie `setosa` con una longitud de sepalo mayor a `4.8`.
Ya realicé los cambios, incluido la tilde.
Nombre: Noemi Alejandra Huarino Anchillo
Motivo: Punto extra en la PC1
Horario: Laboratorio 1.01 (miércoles de 3 a 5pm)

2021-12-19 23:14 UTC, franciscovilchezv approved these changes
+1 PC1

2021-12-19 23:14 UTC, merged

2021-12-20 18:09 UTC, franciscovilchezv commented
Done